[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
jupyterlab = "4.2.5"
plotly = "5.24.0"
dash = "2.18.1"
shifter-pandas = "0.4.0"
pandas = "2.2.2"
statsmodels = "0.14.2"
jupyter-dash = "0.4.2"
jupyter-core = "5.7.2"
certifi = "2024.8.30"
flask = "3.0.3"
tornado = "6.4.1"
requests = "2.32.3"
urllib3 = "2.2.2"
jupyter-server = "2.14.2"
jinja2 = "3.1.4"
idna = "3.10"
werkzeug = "3.0.4"
