[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
jupyterlab = "4.1.8"
plotly = "5.22.0"
dash = "2.16.1"
shifter-pandas = "0.4.0"
pandas = "2.2.2"
statsmodels = "0.14.2"
jupyter-dash = "0.4.2"
jupyter-core = "5.7.2"
certifi = "2024.2.2"
flask = "3.0.3"
tornado = "6.4"
requests = "2.31.0"
urllib3 = "2.2.1"
jupyter-server = "2.14.0"
jinja2 = "3.1.4"
idna = "3.7"
werkzeug = "3.0.3"
