[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
jupyterlab = "4.0.9"
plotly = "5.18.0"
dash = "2.14.2"
shifter-pandas = "0.4.0"
pandas = "2.1.3"
statsmodels = "0.14.0"
jupyter-dash = "0.4.2"
jupyter-core = "5.5.0"
certifi = "2023.11.17"
flask = "3.0.0"
tornado = "6.4"
requests = "2.31.0"
urllib3 = "2.1.0"
jupyter-server = "2.11.2"
