[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
jupyterlab = "4.0.6"
plotly = "5.17.0"
dash = "2.13.0"
shifter-pandas = "0.4.0"
pandas = "1.5.3"
statsmodels = "0.14.0"
jupyter-dash = "0.4.2"
jupyter-core = "5.3.2"
certifi = "2023.7.22"
flask = "2.2.5"
tornado = "6.3.3"
requests = "2.31.0"
