[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'shifter-jupyterlab'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
jupyterlab = "4.0.2"
plotly = "5.14.1"
dash = "2.9.3"
shifter-pandas = "0.2.1"
pandas = "1.5.3"
statsmodels = "0.13.5"
jupyter-dash = "0.4.2"
jupyter-core = "5.3.1"
certifi = "2023.5.7"
flask = "2.2.5"
tornado = "6.3.2"
requests = "2.31.0"
