# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  versions:
    rebuild: False
  black:
    ignore_patterns_re:
      - README\.md
