name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master

    steps:
      - run: sudo apt-get remove python3-debian python3-distro-info
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.TOKEN }}

      - run: git config --global user.email "sbrunner@ci.org"
      - run: git config --global user.name "Snyk auto-fix"

      - run: python3 -m venv ~/.venv
      - run: ~/.venv/bin/pip install --pre c2cciutils[audit]
      - run: python3 -m pip install --pre c2cciutils[audit]

      - name: Check .tool-versions file existence
        id: tool-versions
        uses: andstor/file-existence-action@v2
        with:
          files: .tool-versions
      - uses: asdf-vm/actions/install@v3
        if: steps.tool-versions.outputs.files_exists == 'true'
      - run: cat /tmp/python-build.*.log
        if: failure()
      - run: python --version

      - name: Audit
        run: ~/.venv/bin/c2cciutils-audit --branch=${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
