name: Conventional commits

on:
  pull_request:

jobs:
  build:
    name: Conventional commits
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3
