name: Delete old workflow runs

on:
  schedule:
    - cron: '*/1 * * * *'

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    name: Delete old workflow runs

    steps:
      - run: env
      - run: env
        env:
          GITHUB_EVENT: ${{ toJson(env) }}
      - run: env
        env:
          GITHUB_EVENT: ${{ toJson(github) }}
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          older-than-seconds: 43200000 # 500 days
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
