name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  main:
    runs-on: ubuntu-22.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files
        env:
          SKIP: poetry-lock
      - run: git diff && false
        if: failure()

      - name: Checks
        run: c2cciutils-checks
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - run: python3 -m pip install --user --requirement=requirements.txt
      - run: poetry --version
      - run: poetry export --without-hashes --output=requirements-poetry.txt
      - run: python3 -m pip install --user --no-deps --requirement=requirements-poetry.txt

      - run: scripts/create-pages > index.html

      - run: mkdir gh-pages
      - run: mv *.html gh-pages/

      - uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: gh-pages
        if: startsWith(github.ref, 'refs/heads/') && ! contains(github.ref_name, '/') && env.HAS_SECRETS == 'HAS_SECRETS'

  gh-pages:
    runs-on: ubuntu-22.04
    name: Github Pages
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/heads/') && ! contains(github.ref_name, '/')
    concurrency: gh-pages
    needs:
      - main

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - uses: actions/download-artifact@v3
        with:
          name: gh-pages
          path: ${{ github.ref_name }}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - name: Rewrite root commit and force push
        run: |
          git config --global user.name "Continuous integration"
          git config --global user.email "ci@shifters-ch.org"
          git add ${{ github.ref_name }}
          git commit --message="Add ${{ github.ref_name }} on GitHub pages"
          git push
        if: env.HAS_SECRETS == 'HAS_SECRETS'
