name: Required label

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  build:
    name: Required label
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: yashhy/pr-label-check-and-comment-action@master
        with:
          required_labels: enhancement, bug, refactor, documentation, style, performance, test, build, dependencies
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
