name: Changelog Generator

on:
  push:
    branches:
      - master

jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        uses: fabernovel/github-changelog-generator-action@v1.0.0-alpha02
        with:
          options: --token ${{ secrets.GITHUB_TOKEN }}
