name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: google-github-actions/release-please-action@v3
