name: Changelog Generator

on:
  push:
    branches:
      - master

jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git add CHANGELOG.md
      - run: git config --global user.email "ci@example.com"
      - run: git config --global user.name "CI"
      - run: git commit -m "Update the changelog"
      - run: git checkout -b changelog-update
      - run: git push origin changelog-update -f
      - run: gh pr create --base=master --fill
